### ISSUE TITLE
JVM properties (Max heap, initial heap etc) are hardcoded to the default after build image

### ISSUE THREAD

**Issue by mtavawala** [TIBCOSoftware/be-tools#278] opened 2022-05-07 00:32 UTC
### Version Information
| Software       | Version(s)     |
| -------------- | -------------- |
| BusinessEvents |     6.2.1           |
| OS Type?       |        Linux        |
| OS Version?    |       7.9         |
| Docker         |        20.10.14        |
| Kubernetes     |                |
| Helm           |                |

### What is the expected behavior?
The INITIAL_HEAP_SIZE, MAX_HEAP_SIZE, STACK_SIZE and JAVA_EXTENDED_PROPERTIES properties in the run.sh never equate to a value as the BE_PROPS file does not have an entries related JVM parameters
### Other notes on how to reproduce the issue?
After building an image using the build_image.sh script as using the below command
./build_image.sh -i app -a /Users/mtavawal/workspace/be/docker/PreprocessorBasics2 -s /Users/mtavawal/temp -t mustafat/preprocessorbasicsmultipu:3.0.0 -d ../docker/dockerfiles/Dockerfile.rhel

The JVM properties are copied over from the be-engine.tra available after installation to the last line and the original line is commented out. There is no way to set different values in the be-engine.tra file.

### If the bug is confirmed, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by LakshmiMekala** [comment] 2022-05-10 07:30
Hi @mtavawala


If you want to override heap size, max heap size, stack size and java extended properties, run containter using below command


```
docker run -e "tra.java.heap.size.initial=1024m" -e "tra.java.heap.size.max=1024m" -e "tra.java.stack.size=2m" -e="tra.java.extended.properties=-server -Xms512m -Xmx512m -javaagent:%BE_HOME%/lib/cep-base.jar -XX:MaxMetaspaceSize=512m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC" frauddetection
```

Connect to the running container and inspect be-engie.tra file to cofirm.

docker exec -it `containerID` bash
cat /opt/tibco/be/`be-version`/bin/be-engie.tra


pasting few lines from tra file:
```
# Jars that should be skipped by Tomcat server's TLDJarScanner
tomcat.util.scan.StandardJarScanFilter.jarsToSkip=xdata.jar,tibrvj.jar
java.property.be.engine.cluster.as.discover.url=%AS_DISCOVER_URL%
java.property.be.engine.cluster.as.listen.url=%AS_LISTEN_URL%
java.property.be.engine.cluster.as.remote.listen.url=%AS_REMOTE_LISTEN_URL%
java.property.com.sun.management.jmxremote.rmi.port=%jmx_port%
java.property.java.rmi.server.hostname 172.17.0.2
java.extended.properties=-server -Xms512m -Xmx512m -javaagent:%BE_HOME%/lib/cep-base.jar -XX:MaxMetaspaceSize=512m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Xss2m
java.heap.size.initial=1024m
java.heap.size.max=1024m
```

**Comment by mtavawala** [comment] 2022-05-10 16:54
Hi @LakshmiMekala,

Thanks for the update. Now I understand that JVM parameters need to be passed as environment variables.

Even after doing the same, I see that tra.java.heap.size.initial=512m and tra.java.heap.size.max=2048m only get set in the be-engine.tra

The tra.java.stack.size and tra.java.extended.properties do not get set.

I ran the following command and did not see the be-engine.tra getting updated to use this variable.

`docker run -e PU='BatchOperations' -e "tra.java.extended.properties=-server -Xms512m -Xmx4096m -javaagent:%BE_HOME%/lib/cep-base.jar -XX:MaxMetaspaceSize=512m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC" -p 5555:5555 mustafat/preprocessorbasicsmultipu:6.0.0`

**Comment by rameshpolishetti** [comment] 2022-05-11 03:31
Hi @mtavawala, Can you confirm, if the issue is resolved or do you still need something from our end?

**Comment by mtavawala** [comment] 2022-05-11 18:39
Hi @rameshpolishetti , this issue has been resolved. Thanks for the help.

**Comment by LakshmiMekala** [comment] 2022-05-12 01:58
Closing as per above comments

**Closed by LakshmiMekala** 2022-05-12 01:58 UTC
